volumes:
  local_storage: true
# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false
extra:
  autoRecovery: false

# limit to 1 replica
proxy:
  replicaCount: 1
  service:
    type: ClusterIP
zookeeper:
  replicaCount: 1
bookkeeper:
  replicaCount: 1
  configData:
    diskUsageThreshold: "0.999"
    diskUsageWarnThreshold: "0.999"
    PULSAR_PREFIX_diskUsageThreshold: "0.999"
    PULSAR_PREFIX_diskUsageWarnThreshold: "0.999"
broker:
  replicaCount: 1
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
pulsar_manager:
  service:
    type: ClusterIP
initContainers: {}

toolset:
  useProxy: false
