volumes:
  local_storage: true
# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false
  pulsar_manager: false
extra:
  autoRecovery: false
# disable resources limit & limit to 1 replica
proxy:
  resources: []
  replicaCount: 1
  pdb:
    usePolicy: false
zookeeper:
  resources: []
  replicaCount: 1
  pdb:
    usePolicy: false
bookkeeper:
  resources: []
  replicaCount: 1
  configData:
    diskUsageThreshold: "0.999"
    diskUsageWarnThreshold: "0.999"
    PULSAR_PREFIX_diskUsageThreshold: "0.999"
    PULSAR_PREFIX_diskUsageWarnThreshold: "0.999"
  pdb:
    usePolicy: false
broker:
  resources: []
  replicaCount: 1
  pdb:
    usePolicy: false
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
initContainers:
  resources: []
toolset:
  resources: []
  useProxy: false

# enable TLS
tls:
  enabled: true
  proxy:
    enabled: true
  broker:
    enabled: true
  bookie:
    enabled: true
  zookeeper:
    enabled: true

# disable cert-manager
certs:
  internal_issuer:
    enabled: false
