{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clamapi.fullname" . }}
  labels:
    app: {{ template "clamapi.name" . }}
    chart: {{ template "clamapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{ .Values.podDisruptionBudget.rule.type }}: {{.Values.podDisruptionBudget.rule.value}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clamapi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
