apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "proxy-relay.fullname" . }}
  labels:
{{ include "proxy-relay.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "proxy-relay.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "proxy-relay.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "proxy-relay.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.extraEnv .Values.secretEnv}}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.secretEnv }}
            {{- range .Values.secretEnv }}
            {{- $secretName := .secretName }}
            {{- range $key, $value :=  .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $value }}
                  {{- end }}
                  {{- end }}
                  {{- end }}
                  {{- end }}
          volumeMounts:
            - mountPath: /usr/local/apache2/conf/httpd.conf
              name: config
              subPath: httpd.conf
            - mountPath: /usr/local/apache2/conf/extra/proxy-html.conf
              name: config
              subPath: proxy-html.conf
            {{- if .Values.luaHandlers }}
            - mountPath: /usr/local/apache2/conf/extra/handlers.lua
              name: config
              subPath: handlers.lua
            {{- end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
