{{- if .Values.hpa -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "proxy-relay.fullname" . }}
  labels:
{{ include "proxy-relay.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "proxy-relay.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hpa.cpuMax }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.hpa.memoryMax }}
  {{- end }}
