{{- if .Values.frontend.ingress.enabled -}}
{{- $fullName := include "dependency-track.fullname" . -}}
{{- $ingressPath := .Values.frontend.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "dependency-track.labels" . | indent 4 }}
{{- with .Values.frontend.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.frontend.ingress.tls }}
  tls:
  {{- range .Values.frontend.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.frontend.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-frontend
              servicePort: http
          - path: {{ $ingressPath }}api
            backend:
              serviceName: {{ $fullName }}-backend
              servicePort: http

  {{- end }}
{{- end }}
