client:
  replicas: 1
  resources:
    requests:
      cpu: null
      memory: null
data:
  replicas: 1
  resources:
    requests: null
master:
  replicas: 1
  resources:
    requests: null
logstash:
  replicas: 1
  resources:
    requests: null
filebeat:
  replicas: 1
  resources:
    requests: null
kibana:
  replicas: 1
  resources:
    requests: null
