{{- $chartName := include "default-chart.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "default-chart.fullname" . }}
  labels:
    {{- include "default-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "default-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "default-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "default-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- /* Variable environnement specifique au pod*/}}
            {{- range $key, $value :=  .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- /* Variable d'environnements issues de la liste des secrets*/}}
            {{- range .Values.secretsEnv }}
            {{- $secretName := .secretName }}
            {{- range $key, $value :=  .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            {{- range .Values.persistence.volumes }}
            - mountPath: {{ .mountPoint }}
              name: {{ .name }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
    {{- end }}
{{- if and .Values.persistence.enabled }}
      volumes:
        {{- range .Values.persistence.volumes }}
        - name: {{ .name }}
          {{- if .secretName }}
          secret:
            secretName: {{ .secretName }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ $chartName }}-{{ .name }}
          {{- end }}
        {{- end }}
      {{- end }}
