{{- if .Values.podDisruptionBudget.enabled -}}
{{- $kubeVer := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.21-0" $kubeVer -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "default-chart.fullname" . }}
  labels:
{{ include "default-chart.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "default-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}
