apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}-http
  labels:
{{ include "maildev.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - port: {{ .Values.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "maildev.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
