apiVersion: v2
name: passbolt
type: application
version: 1.0.4
appVersion: "2.13.5-debian"
description: A Helm chart to deploy Passbolt
home: http://passbolt.com
sources:
- https://github.com/cnieg/helm-charts/tree/master/charts/passbolt
- https://github.com/passbolt
maintainers:
- name: CNIEG
  email: maintainers@cnieg.fr
dependencies:
- name: mariadb
  version: "8.0.7"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mariadb.enabled
