{{- if .Values.extra.pulsar_manager }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.pulsar_manager.component }}
    cluster: {{ template "pulsar.fullname" . }}
  annotations:
{{ toYaml .Values.pulsar_manager.service.annotations | indent 4 }}
spec:
  type: {{ .Values.pulsar_manager.service.type }}
  ports:
{{ toYaml .Values.pulsar_manager.service.ports | indent 2 }}
  selector:
    app: {{ template "pulsar.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.pulsar_manager.component }}
  {{- end }}