{{- if .Values.pulsar_manager.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
  annotations:
  {{- with .Values.pulsar_manager.ingress.annotations }}
{{ toYaml . | indent 4 }}
  {{- end }}
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
spec:
  {{- if .Values.pulsar_manager.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.pulsar_manager.ingress.hostname }}
      {{- with .Values.pulsar_manager.ingress.tls.secretName }}
      secretName: {{ . }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ required "pulsar_manager ingress hostname not provided" .Values.pulsar_manager.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.pulsar_manager.ingress.path }}
            backend:
              serviceName: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
              servicePort: {{ .Values.pulsar_manager.ingress.port }}
  {{- end }}